var searchData=
[
  ['this_20is_20header',['This is header',['../md_markdown_intro1.html',1,'']]],
  ['tags',['Tags',['../md_markdown_tags.html',1,'']]],
  ['topic_3a_20coding',['Topic: Coding',['../md_markdown_topic_coding.html',1,'']]],
  ['topic_3a_20configuration_20and_20building',['Topic: Configuration and building',['../md_markdown_topic_configuration_and_building.html',1,'']]],
  ['topic_3a_20configuration_20and_20builds',['Topic: Configuration and builds',['../md_markdown_topic_configuration_and_builds.html',1,'']]],
  ['topic_3a_20continuous_20integration_20testing',['Topic: Continuous Integration Testing',['../md_markdown_topic_continuous_integration_testing.html',1,'']]],
  ['topic_3a_20deployment',['Topic: Deployment',['../md_markdown_topic_deployment.html',1,'']]],
  ['topic_3a_20development',['Topic: Development',['../md_markdown_topic_development.html',1,'']]],
  ['topic_3a_20development_20tools',['Topic: Development Tools',['../md_markdown_topic_development_tools.html',1,'']]],
  ['topic_3a_20documentation',['Topic: Documentation',['../md_markdown_topic_documentation.html',1,'']]],
  ['topic_3a_20funding_20sources_20and_20programs',['Topic: Funding Sources and Programs',['../md_markdown_topic_funding_sources_and_programs.html',1,'']]],
  ['topic_3a_20improving_20productivity_20and_20sustainability',['Topic: Improving Productivity and Sustainability',['../md_markdown_topic_improving_productivity_and_sustanability.html',1,'']]],
  ['topic_3a_20licensing',['Topic: Licensing',['../md_markdown_topic_licensing.html',1,'']]],
  ['topic_3a_20performance',['Topic: Performance',['../md_markdown_topic_performance.html',1,'']]],
  ['topic_3a_20performance_20portability',['Topic: Performance Portability',['../md_markdown_topic_performance_portability.html',1,'']]],
  ['topic_3a_20personal_20kanban',['Topic: Personal Kanban',['../md_markdown_topic_personal_kanban.html',1,'']]],
  ['topic_3a_20personal_20productivity_20and_20sustainability',['Topic: Personal Productivity and Sustainability',['../md_markdown_topic_personal_productivity_and_sustainability.html',1,'']]],
  ['topic_3a_20portability',['Topic: Portability',['../md_markdown_topic_portability.html',1,'']]],
  ['topic_3a_20projects_20and_20organizations',['Topic: Projects and Organizations',['../md_markdown_topic_projects_and_organizations.html',1,'']]],
  ['topic_3a_20publication',['Topic: Publication',['../md_markdown_topic_publication.html',1,'']]],
  ['topic_3a_20reliability',['Topic: Reliability',['../md_markdown_topic_reliability.html',1,'']]],
  ['topic_3a_20reproducibility',['Topic: Reproducibility',['../md_markdown_topic_reproducibility.html',1,'']]],
  ['topic_3a_20requirements',['Topic: Requirements',['../md_markdown_topic_requirements.html',1,'']]],
  ['topic_3a_20software_20development',['Topic: Software Development',['../md_markdown_topic_software_development.html',1,'']]],
  ['topic_3a_20software_20engineering',['Topic: Software Engineering',['../md_markdown_topic_software_engineering.html',1,'']]],
  ['topic_3a_20software_20interoperability',['Topic: Software Interoperability',['../md_markdown_topic_software_interoperability.html',1,'']]],
  ['topic_3a_20software_20publishing_20and_20citation',['Topic: Software Publishing and Citation',['../md_markdown_topic_software_publishing_and_citation.html',1,'']]],
  ['topic_3a_20strategies_20for_20more_20effective_20teams',['Topic: Strategies for more effective teams',['../md_markdown_topic_stategies_for_more_effective_teams.html',1,'']]],
  ['topic_3a_20testing',['Topic: Testing',['../md_markdown_topic_testing.html',1,'']]],
  ['topic_3a_20tools',['Topic: Tools',['../md_markdown_topic_tools.html',1,'']]],
  ['topic_3a_20version_20control',['Topic: Version control',['../md_markdown_topic_version_control.html',1,'']]],
  ['topic',['Topic',['../md_markdown_topics.html',1,'']]],
  ['tags_2emd',['tags.md',['../tags_8md.html',1,'']]],
  ['topic_5fcoding_2emd',['topic_coding.md',['../topic__coding_8md.html',1,'']]],
  ['topic_5fconfiguration_5fand_5fbuilding_2emd',['topic_configuration_and_building.md',['../topic__configuration__and__building_8md.html',1,'']]],
  ['topic_5fconfiguration_5fand_5fbuilds_2emd',['topic_configuration_and_builds.md',['../topic__configuration__and__builds_8md.html',1,'']]],
  ['topic_5fcontinuous_5fintegration_5ftesting_2emd',['topic_continuous_integration_testing.md',['../topic__continuous__integration__testing_8md.html',1,'']]],
  ['topic_5fdeployment_2emd',['topic_deployment.md',['../topic__deployment_8md.html',1,'']]],
  ['topic_5fdevelopment_2emd',['topic_development.md',['../topic__development_8md.html',1,'']]],
  ['topic_5fdevelopment_5ftools_2emd',['topic_development_tools.md',['../topic__development__tools_8md.html',1,'']]],
  ['topic_5fdocumentation_2emd',['topic_documentation.md',['../topic__documentation_8md.html',1,'']]],
  ['topic_5ffunding_5fsources_5fand_5fprograms_2emd',['topic_funding_sources_and_programs.md',['../topic__funding__sources__and__programs_8md.html',1,'']]],
  ['topic_5fimproving_5fproductivity_5fand_5fsustanability_2emd',['topic_improving_productivity_and_sustanability.md',['../topic__improving__productivity__and__sustanability_8md.html',1,'']]],
  ['topic_5flicensing_2emd',['topic_licensing.md',['../topic__licensing_8md.html',1,'']]],
  ['topic_5fperformance_2emd',['topic_performance.md',['../topic__performance_8md.html',1,'']]],
  ['topic_5fperformance_5fportability_2emd',['topic_performance_portability.md',['../topic__performance__portability_8md.html',1,'']]],
  ['topic_5fpersonal_5fkanban_2emd',['topic_personal_kanban.md',['../topic__personal__kanban_8md.html',1,'']]],
  ['topic_5fpersonal_5fproductivity_5fand_5fsustainability_2emd',['topic_personal_productivity_and_sustainability.md',['../topic__personal__productivity__and__sustainability_8md.html',1,'']]],
  ['topic_5fportability_2emd',['topic_portability.md',['../topic__portability_8md.html',1,'']]],
  ['topic_5fprojects_5fand_5forganizations_2emd',['topic_projects_and_organizations.md',['../topic__projects__and__organizations_8md.html',1,'']]],
  ['topic_5fpublication_2emd',['topic_publication.md',['../topic__publication_8md.html',1,'']]],
  ['topic_5freliability_2emd',['topic_reliability.md',['../topic__reliability_8md.html',1,'']]],
  ['topic_5freproducibility_2emd',['topic_reproducibility.md',['../topic__reproducibility_8md.html',1,'']]],
  ['topic_5frequirements_2emd',['topic_requirements.md',['../topic__requirements_8md.html',1,'']]],
  ['topic_5fsoftware_5fdevelopment_2emd',['topic_software_development.md',['../topic__software__development_8md.html',1,'']]],
  ['topic_5fsoftware_5fengineering_2emd',['topic_software_engineering.md',['../topic__software__engineering_8md.html',1,'']]],
  ['topic_5fsoftware_5finteroperability_2emd',['topic_software_interoperability.md',['../topic__software__interoperability_8md.html',1,'']]],
  ['topic_5fsoftware_5fpublishing_5fand_5fcitation_2emd',['topic_software_publishing_and_citation.md',['../topic__software__publishing__and__citation_8md.html',1,'']]],
  ['topic_5fstategies_5ffor_5fmore_5feffective_5fteams_2emd',['topic_stategies_for_more_effective_teams.md',['../topic__stategies__for__more__effective__teams_8md.html',1,'']]],
  ['topic_5ftesting_2emd',['topic_testing.md',['../topic__testing_8md.html',1,'']]],
  ['topic_5ftools_2emd',['topic_tools.md',['../topic__tools_8md.html',1,'']]],
  ['topic_5fversion_5fcontrol_2emd',['topic_version_control.md',['../topic__version__control_8md.html',1,'']]],
  ['topics_2emd',['topics.md',['../topics_8md.html',1,'']]]
];
