var searchData=
[
  ['topic',['Topic',['../md_markdown_topic.html',1,'']]],
  ['topic_3a_20coding',['Topic: Coding',['../md_markdown_topic_coding.html',1,'']]],
  ['topic_3a_20configuration_20and_20building',['Topic: Configuration and building',['../md_markdown_topic_configuration_and_building.html',1,'']]],
  ['topic_3a_20configuration_20and_20builds',['Topic: Configuration and builds',['../md_markdown_topic_configuration_and_builds.html',1,'']]],
  ['topic_3a_20continuous_20integration_20testing',['Topic: Continuous Integration Testing',['../md_markdown_topic_continuous_integration_testing.html',1,'']]],
  ['topic_3a_20deployment',['Topic: Deployment',['../md_markdown_topic_deployment.html',1,'']]],
  ['topic_3a_20development',['Topic: Development',['../md_markdown_topic_development.html',1,'']]],
  ['topic_3a_20development_20tools',['Topic: Development Tools',['../md_markdown_topic_development_tools.html',1,'']]],
  ['topic_3a_20documentation',['Topic: Documentation',['../md_markdown_topic_documentation.html',1,'']]],
  ['topic_3a_20funding_20sources_20and_20programs',['Topic: Funding Sources and Programs',['../md_markdown_topic_funding_sources_and_programs.html',1,'']]],
  ['topic_3a_20improving_20productivity_20and_20sustainability',['Topic: Improving Productivity and Sustainability',['../md_markdown_topic_improving_productivity_and_sustanability.html',1,'']]],
  ['topic_3a_20licensing',['Topic: Licensing',['../md_markdown_topic_licensing.html',1,'']]],
  ['topic_3a_20performance',['Topic: Performance',['../md_markdown_topic_performance.html',1,'']]],
  ['topic_3a_20performance_20portability',['Topic: Performance Portability',['../md_markdown_topic_performance_portability.html',1,'']]],
  ['topic_3a_20personal_20kanban',['Topic: Personal Kanban',['../md_markdown_topic_personal_kanban.html',1,'']]],
  ['topic_3a_20personal_20productivity_20and_20sustainability',['Topic: Personal Productivity and Sustainability',['../md_markdown_topic_personal_productivity_and_sustainability.html',1,'']]],
  ['topic_3a_20portability',['Topic: Portability',['../md_markdown_topic_portability.html',1,'']]],
  ['topic_3a_20projects_20and_20organizations',['Topic: Projects and Organizations',['../md_markdown_topic_projects_and_organizations.html',1,'']]],
  ['topic_3a_20publication',['Topic: Publication',['../md_markdown_topic_publication.html',1,'']]],
  ['topic_3a_20reliability',['Topic: Reliability',['../md_markdown_topic_reliability.html',1,'']]],
  ['topic_3a_20reproducibility',['Topic: Reproducibility',['../md_markdown_topic_reproducibility.html',1,'']]],
  ['topic_3a_20requirements',['Topic: Requirements',['../md_markdown_topic_requirements.html',1,'']]],
  ['topic_3a_20software_20development',['Topic: Software Development',['../md_markdown_topic_software_development.html',1,'']]],
  ['topic_3a_20software_20engineering',['Topic: Software Engineering',['../md_markdown_topic_software_engineering.html',1,'']]],
  ['topic_3a_20software_20interoperability',['Topic: Software Interoperability',['../md_markdown_topic_software_interoperability.html',1,'']]],
  ['topic_3a_20software_20publishing_20and_20citation',['Topic: Software Publishing and Citation',['../md_markdown_topic_software_publishing_and_citation.html',1,'']]],
  ['topic_3a_20strategies_20for_20more_20effective_20teams',['Topic: Strategies for more effective teams',['../md_markdown_topic_stategies_for_more_effective_teams.html',1,'']]],
  ['topic_3a_20testing',['Topic: Testing',['../md_markdown_topic_testing.html',1,'']]],
  ['topic_3a_20tools',['Topic: Tools',['../md_markdown_topic_tools.html',1,'']]],
  ['topic_3a_20version_20control',['Topic: Version control',['../md_markdown_topic_version_control.html',1,'']]]
];
