var NAVTREE =
[
  [ "Better Scientific Software", "index.html", [
    [ "Category", "md_markdown_category.html", null ],
    [ "Category: Collaboration", "md_markdown_category_collaboration.html", null ],
    [ "Category: Collaborations", "md_markdown_category_collaborations.html", null ],
    [ "Category: Crosscutting", "md_markdown_category_crosscutting.html", null ],
    [ "Category: Development", "md_markdown_category_development.html", null ],
    [ "Category: Individual Productivity", "md_markdown_category_individual_productivity.html", null ],
    [ "Category: Performance", "md_markdown_category_performance.html", null ],
    [ "Category: Planning", "md_markdown_category_planning.html", null ],
    [ "Category: Reliability", "md_markdown_category_reliability.html", null ],
    [ "Category: Skills", "md_markdown_category_skills.html", null ],
    [ "Level", "md_markdown_level.html", null ],
    [ "Level 0", "md_markdown_level0.html", null ],
    [ "Level 1", "md_markdown_level1.html", null ],
    [ "Level 2", "md_markdown_level2.html", null ],
    [ "Tag: Blog", "md_markdown_tag_blog.html", null ],
    [ "Tag: Book", "md_markdown_tag_book.html", null ],
    [ "Tag: BSSW-Internal", "md_markdown_tag_bssw-internal.html", null ],
    [ "Tag: Conferences", "md_markdown_tag_conferences.html", null ],
    [ "Tag: Containers", "md_markdown_tag_containers.html", null ],
    [ "Tag: Docker", "md_markdown_tag_docker.html", null ],
    [ "Tag: Document", "md_markdown_tag_document.html", null ],
    [ "Tag: Documentation", "md_markdown_tag_documentation.html", null ],
    [ "Tag: Doxygen", "md_markdown_tag_doxygen.html", null ],
    [ "Tag: Event", "md_markdown_tag_event.html", null ],
    [ "Tag: Fellowship program", "md_markdown_tag_fellowship_program.html", null ],
    [ "Tag: Funding Agency", "md_markdown_tag_funding_agency.html", null ],
    [ "Tag: Funding Program", "md_markdown_tag_funding_program.html", null ],
    [ "Tag: Howto", "md_markdown_tag_howto.html", null ],
    [ "Tag: HPC", "md_markdown_tag_hpc.html", null ],
    [ "Tag: Improving productivity and sustainability", "md_markdown_tag_improving_productivity_and_sustainability.html", null ],
    [ "Tag: Journal", "md_markdown_tag_journal.html", null ],
    [ "Tag: Libraries", "md_markdown_tag_libraries.html", null ],
    [ "Tag: Meta", "md_markdown_tag_meta.html", null ],
    [ "Tag: Minisymposium", "md_markdown_tag_minisymposium.html", null ],
    [ "Tag: Minisymposterim", "md_markdown_tag_minisymposterim.html", null ],
    [ "Tag: Organization", "md_markdown_tag_organization.html", null ],
    [ "Tag: Paper", "md_markdown_tag_paper.html", null ],
    [ "Tag: Podcast Episode", "md_markdown_tag_podcast-episode.html", null ],
    [ "Tag: Poster", "md_markdown_tag_poster.html", null ],
    [ "Tag: Project", "md_markdown_tag_project.html", null ],
    [ "Tag: Reliability", "md_markdown_tag_reliability.html", null ],
    [ "Tag: Reproducibility", "md_markdown_tag_reproducibility.html", null ],
    [ "Tag: Robustness", "md_markdown_tag_robustness.html", null ],
    [ "Tag: Service", "md_markdown_tag_service.html", null ],
    [ "Tag: Terminology", "md_markdown_tag_terminology.html", null ],
    [ "Tag: Tool", "md_markdown_tag_tool.html", null ],
    [ "Tag: Training", "md_markdown_tag_training.html", null ],
    [ "Tag: Tutorial", "md_markdown_tag_tutorial.html", null ],
    [ "Tag: Video", "md_markdown_tag_video.html", null ],
    [ "Tag: Vision", "md_markdown_tag_vision.html", null ],
    [ "Tag: Webinar", "md_markdown_tag_webinar.html", null ],
    [ "Tag: Website", "md_markdown_tag_website.html", null ],
    [ "Tag: Whatis", "md_markdown_tag_whatis.html", null ],
    [ "Tag: Workshop Series", "md_markdown_tag_workshop-series.html", null ],
    [ "Tag: Workshop", "md_markdown_tag_workshop.html", null ],
    [ "Tags", "md_markdown_tags.html", null ],
    [ "Topic: Coding", "md_markdown_topic_coding.html", null ],
    [ "Topic: Configuration and building", "md_markdown_topic_configuration_and_building.html", null ],
    [ "Topic: Configuration and builds", "md_markdown_topic_configuration_and_builds.html", null ],
    [ "Topic: Continuous Integration Testing", "md_markdown_topic_continuous_integration_testing.html", null ],
    [ "Topic: Deployment", "md_markdown_topic_deployment.html", null ],
    [ "Topic: Development", "md_markdown_topic_development.html", null ],
    [ "Topic: Development Tools", "md_markdown_topic_development_tools.html", null ],
    [ "Topic: Documentation", "md_markdown_topic_documentation.html", null ],
    [ "Topic: Funding Sources and Programs", "md_markdown_topic_funding_sources_and_programs.html", null ],
    [ "Topic: Improving Productivity and Sustainability", "md_markdown_topic_improving_productivity_and_sustanability.html", null ],
    [ "Topic: Licensing", "md_markdown_topic_licensing.html", null ],
    [ "Topic: Performance", "md_markdown_topic_performance.html", null ],
    [ "Topic: Performance Portability", "md_markdown_topic_performance_portability.html", null ],
    [ "Topic: Personal Kanban", "md_markdown_topic_personal_kanban.html", null ],
    [ "Topic: Personal Productivity and Sustainability", "md_markdown_topic_personal_productivity_and_sustainability.html", null ],
    [ "Topic: Portability", "md_markdown_topic_portability.html", null ],
    [ "Topic: Projects and Organizations", "md_markdown_topic_projects_and_organizations.html", null ],
    [ "Topic: Publication", "md_markdown_topic_publication.html", null ],
    [ "Topic: Reliability", "md_markdown_topic_reliability.html", null ],
    [ "Topic: Reproducibility", "md_markdown_topic_reproducibility.html", null ],
    [ "Topic: Requirements", "md_markdown_topic_requirements.html", null ],
    [ "Topic: Software Development", "md_markdown_topic_software_development.html", null ],
    [ "Topic: Software Engineering", "md_markdown_topic_software_engineering.html", null ],
    [ "Topic: Software Interoperability", "md_markdown_topic_software_interoperability.html", null ],
    [ "Topic: Software Publishing and Citation", "md_markdown_topic_software_publishing_and_citation.html", null ],
    [ "Topic: Strategies for more effective teams", "md_markdown_topic_stategies_for_more_effective_teams.html", null ],
    [ "Topic: Testing", "md_markdown_topic_testing.html", null ],
    [ "Topic: Tools", "md_markdown_topic_tools.html", null ],
    [ "Topic: Version control", "md_markdown_topic_version_control.html", null ],
    [ "Topic", "md_markdown_topics.html", null ],
    [ "Namespaces", null, [
      [ "Namespace List", "namespaces.html", "namespaces" ],
      [ "Namespace Members", "namespacemembers.html", [
        [ "All", "namespacemembers.html", null ],
        [ "Functions", "namespacemembers_func.html", null ]
      ] ]
    ] ],
    [ "Files", null, [
      [ "File List", "files.html", "files" ]
    ] ]
  ] ]
];

var NAVTREEINDEX =
[
"dir_b8a629b4a32964089411333772c68dab.html"
];

var SYNCONMSG = 'click to disable panel synchronisation';
var SYNCOFFMSG = 'click to enable panel synchronisation';